server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/asset_management?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  jackson:
    default-property-inclusion: non_null
